### ISSUE TITLE
Caching request

### ISSUE THREAD

**Issue by pennybuster** [twisted1919/evs-go#4]
Hi there. Please implement some kind of caching for checked email addresses.
By the way, I've read about Mailwizz. Looks pretty neat. Is it possible to integrate this email checker with it?
Thanks!

**Comment by twisted1919** [comment]
@pennybuster - there is already a cache mechanism in place, see https://github.com/twisted1919/evs-go/blob/master/main.go#L377 so setting `emails.cache.enabled` to true will do it.

This checker will work with mailwizz just fine, you just have to create the code to connect the two.

**Comment by pennybuster** [comment]
Thank you :+1:
